[[smcfiss]]
== "Smcfiss" Extension for Machine-mode Shadow Stack, Version 0.1

The Smcfiss extension enables the use of a shadow stack to enforce
backward-edge control-flow integrity in machine mode.

The Smcfiss extension depends on the Zicfiss extension.

The Smcfiss extension introduces an `MSSE` field in `mseccfg` to enable the use
of Zicfiss in machine mode. When the Smcfiss extension is implemented, the
shadow-stack-enabled (SSE) state, denoted by the term `xSSE`, is set to the
value of `mseccfg.MSSE`.

When `mseccfg.MSSE` is 0, the implementation behaves as if the Smcfiss is not
implemented. When `mseccfg.MSSE` is 1, Zicfiss instructions are enabled for use
in machine mode.

The Smcfiss extension introduces a new 6-bit WARL field, `SSPMP`, in the
`mseccfg` register to designate a PMP entry for use as a machine-mode
shadow stack memory region.

When the Smpepmp extension is implemented and `mseccfg.RLB` is 0 while
`pmpcfg.L` is 1 in any PMP entry, `mseccfg.SSPMP` becomes locked, and
further writes to `mseccfg.SSPMP` and `mseccfg.MSSE` are ignored
until a PMP reset.

When `mseccfg.MSSE` is 1, the PMP entry identified by `mseccfg.SSPMP`
designates a machine-mode shadow-stack region if `pmpcfg[SSPMP].LXWR` is
`1010`. When the Smepmp extension is implemented, this designation applies
regardless of the value of `mseccfg.MML`. For the PMP entry designated by
`mseccfg.SSPMP`, all other encodings of the `LXWR` field are reserved for
future standard use.

The following additional rules apply to memory accesses when the effective
privilege mode is M and `mseccfg.MSSE` is 1:

* Shadow stack instructions may only access the machine-mode shadow stack
  region. Any shadow stack instruction that attempts to access memory
  outside this region raises a store/AMO access-fault exception.
* Instructions other than shadow stack instructions are not permitted to
  store to the machine-mode shadow stack region. Any such attempt raises a
  store/AMO access-fault exception.
* Implicit accesses, including instruction fetches, to the machine-mode
  shadow stack region raise an access-fault exception corresponding to the
  original access type.
* The machine-mode shadow stack region may be read either by explicit load
  instructions or by shadow stack instructions.

Accesses to a machine-mode shadow stack region with effective privilege
mode less than M raise an access-fault exception corresponding to the
original access type.

[NOTE]
====
When the Smepmp is implemented, the recommended sequence to clear `mseccfg.MSSE`
is to first set the `LXWR` field of the PMP entry identified by `SSPMP` to
`0000`. This ordering avoids the possibility of the memory region being
temporarily interpreted as an ordinary, shared, and executable region.
====

== "Sspmpss" Extension for S-level PMP Shadow Stack, Version 0.1

The Sspmpss extension enables the use of a shadow stack to enforce
backward-edge control-flow integrity in supervisor and user mode using S-level
PMPs (SPMP). The Sspmpss extension depends on the Zicfiss and Sspmp extensions.

If `satp.MODE` is not `Bare` or if `menvcfg.SSE` is 0, the implementation
behaves as if Sspmpss is not implemented.

When Sspmpss is implemented, the following additional rules apply to memory
accesses with effective privilege mode less than M:

* The `XWR=010` encoding in `spmpcfg[i]` register is defined to represent a
  shadow stack memory region.
* Shadow stack instructions may only access the shadow stack regions. Any
  shadow stack instruction that attempts to access a memory outside that is
  not a shadow stack memory region raises a store/AMO access-fault exception.
* Instructions other than shadow stack instructions are not permitted to
  store to the shadow stack memory regions. Any such attempt raises a
  store/AMO access-fault exception.
* Implicit accesses, including instruction fetches, to a shadow stack memory
  region raise an access-fault exception corresponding to the original access
  type.
* The shadow stack memory regions may be read either by explicit load
  instructions or by shadow stack instructions.

The access faults caused by these additional rules occur at lower priority than
a page fault due to memory access being disallowed by the U bit given the
effective privilege mode of the access and the state of the `SUM` and `MXR`
fields of the `mstatus` register.
