== "Zvzip" Extension for Reordering Structured Data, Version 0.1

This chapter describes the Zvzip standard extension for reordering structured
data in vector registers. These instruction address usages such as packing and
unpacking data structures such as color components of a pixel, real and
imaginary components of complex numbers, transposing small matrices, among
others.

=== Vector Zip Even and Zip Odd Instructions

The vector zip-even instruction interleaves the even-indexed elements of the
source vector register groups into the destination vector register group.

The vector zip-odd instruction interleaves the odd-indexed elements of the
source vector register groups into the destination vector register group.

The destination register cannot overlap the source registers and, if masked,
cannot overlap the mask register.

----
vzipe.vv vd, vs2, vs1, vm  # vd[i] = (i % 2) == 0 ? vs2[i + 0] : vs1[i - 1]
vzipo.vv vd, vs2, vs1, vm  # vd[i] = (i % 2) == 0 ? vs2[i + 1] : vs1[i + 0]
----

[NOTE]
====
vzipo may read one element past VL in vs2 if VL is odd.
====

=== Vector Zip Instruction

The vector zip instruction interleaves element at a given index in each
source vector register group, in destination vector register group. This
instruction operates with an effective vector length of 2*VL. The destination
EMUL is 2xLMUL. The instruction is reserved when LMUL is 8. 

The destination register cannot overlap the source registers and, if masked,
cannot overlap the mask register.

----
vzip.vv vd, vs2, vs1, vm   # for i in 0 to 2*VL
                           #   vd[i] = (i % 2 == 0) ? vs2[i/2] : vs1[i/2]
----

=== Vector Extract Even and Unpack Odd Instructions

The vector extract-even instruction extracts the VL number of even-indexed elements
from the source vector register group into the destination vector register group.

The vector extract-odd instruction extracts the VL number of odd-indexed elements
from the source vector register group into the destination vector register group.

These instructions access 2*VL number of elements in the source vector register
group and the source EMUL is 2xLMUL. The instruction is reserved when LMUL is 8. 

The destination register cannot overlap the source registers and, if masked,
cannot overlap the mask register.

----
vextre.vv vd, vs2, vs1, vm  # vd[i] = vs1[(2 * i)]
vextro.vv vd, vs2, vs1, vm  # vd[i] = vs1[((2 * i) + 1)]
----
